### ISSUE TITLE
Implement reciprocal scaling

### ISSUE THREAD

**Issue by weslleyspereira** [tlapack/tlapack#139]
Reciprocal scaling is `x := x/alpha`, where x is an array. This operation is, in most cases, preferable to more `x := (1/alpha)*x`. For instance, the former has less accumulation error.

The technical report on the BLAS Standard, https://netlib.org/blas/blast-forum/blas-report.pdf, proposes the reciprocal scaling to be part of the BLAS. The current LAPACK code has its implementation of RSCL, but it relies on applying the BLAS SCAL to (1/alpha). MKL, for instance, has its own implementation of RSCL.

I think we should have a tlapack::rscl. I can propose the PR. Also, I can propose the PR in LAPACK++ so we can access code from MKL and other optimized libraries.

**Comment by langou** [comment]
All good with me. 

My preference would be that this goes in BLAS++ instead of LAPACK++. But I do not have a strong opinion.

@mgates3.

**Comment by mgates3** [comment]
Are you proposing that we add an implementation of `rscl` (or `rscale`,  in BLAS++, or just a wrapper around these LAPACK routines:
```
SRC/csrscl.f
SRC/drscl.f
SRC/srscl.f
SRC/zdrscl.f
```
While `rscl` is BLAS-like, it exists solely in LAPACK, so I would tend to put it in LAPACK++. Until recently, we put routines in BLAS++ only if they exist in LAPACK/BLAS/SRC (i.e., in `-lblas`). But this is annoying with routines like `[cz]rot`, `[cz]symv`, and `[cz]syr` that are in LAPACK but the real precisions `[sd]rot`, `[sd]symv`, `[sd]syr` are in BLAS. So recently I'm proposing that we put these in BLAS++ and just require linking with both `-llapack -lblas`.
Cf. https://bitbucket.org/icl/blaspp/pull-requests/44/removes-crot-and-zrot-since-they-are-not
But since all versions of `rscl` are in LAPACK, I would keep it in LAPACK++.

There are also these:
```
SRC/clarscl2.f
SRC/dlarscl2.f
SRC/slarscl2.f
SRC/zlarscl2.f
```
`ZLARSCL2` says it does "scaling on a vector", but from the arguments `(M, N, D, X, LDX)` it's pretty clear that X is a matrix, not a vector. The docs are super confusing: "The leading dimension of the vector X. LDX >= M." I assume it should be "matrix" instead of "vector".

**Comment by weslleyspereira** [comment]
> There are also these:
> 
> ```
> SRC/clarscl2.f
> SRC/dlarscl2.f
> SRC/slarscl2.f
> SRC/zlarscl2.f
> ```
> 
> `ZLARSCL2` says it does "scaling on a vector", but from the arguments `(M, N, D, X, LDX)` it's pretty clear that X is a matrix, not a vector. The docs are super confusing: "The leading dimension of the vector X. LDX >= M." I assume it should be "matrix" instead of "vector".

Thanks for indicating this issue. Could you open an issue on LAPACK? I also believe it should read "matrix" instead of "vector".

**Comment by mgates3** [comment]
BTW, to create a new wrapper for LAPACK++, see `tools/wrapper_gen.py`. It's documented in the script. That handles only routines with 1 data-type prefix like `drscl`, not ones with 2 data-type prefixes like `zdrscl`. The quick workaround that I found is to temporarily in LAPACK rename the files:
```
lapack/SRC> mv zdrscl.f zrscl.f
lapack/SRC> mv csrscl.f crscl.f
```
The wrappers probably need some fixing, but that should give a good head start.

**Comment by mgates3** [comment]
See https://github.com/Reference-LAPACK/lapack/issues/733
