### ISSUE TITLE
workspace compilation issues

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#193]
`gelqf` contains an example of when we can use a submatrix as workspace.

```c++
workspace_opts_t<void> workopts(
            slice(TT, range(j, m), range(0, ib)));
larfb(Side::Right, Op::NoTrans, Direction::Forward, StoreV::Rowwise,
      A11, TT1, A12, workopts);
```

If i try to pass that same workspace to `gelq2`, compilation fails.

The following does work (removing `<void>`) but i don't fully understand why.

```c++
workspace_opts_t workopts(
            slice(TT, range(j, m), range(0, ib)));
gelq2(A11, tauw1, gelq2Opts);
```

**Comment by weslleyspereira** [comment]
This is the expected behavior so far. The types `workspace_opts_t<void>` and `workspace_opts_t<>` are distinct. `larfb` expects `workspace_opts_t<T>` and `gelq2` expects `workspace_opts_t<>`.

`workspace_opts_t` is a variadic template struct, and that was done mainly for allowing the choice via interface of the matrix type that will give shape to a workspace. This is currently used in `larfb` and `unmqr`. Currently, `gehqr` uses `larfb` with a specific kind of shape:

https://github.com/tlapack/tlapack/blob/7768d6b7ec5354dc2c1e8fdc43149217dff32551/include/tlapack/lapack/gehrd.hpp#L161

I am working on a section about the workspace design right now. I will make sure this explanation is there.
