### ISSUE TITLE
Enhancement: Concepts

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#197]
I would really (really) like to use c++20 concepts.

### Better error messages

Let's take `lange` as an example

If you use the following (incorrect) code to calculate the norm of a vector:
```c++
std::vector v(20);
auto nrm = lange( Norm::Max, v); 
```
`lange` expects a matrix, not a vector, so this will error, but it doesn't error where you expect it to error (the line where you call it with a vector), instead, it errors inside of `lange`, because there it will attempt to use functions like `nrows` that only work for matrices.

If we define a concept `Matrix`, the compiler would be able to tell at the correct line what the real mistake is. This is not only nice for us as library developers, but pretty much necessary if we want average users to use <T>LAPACK. I do not want them to see error messages coming from somewhere inside the library.

### More possibilities for overloading

What if we want `lange` to work for vectors as well. We could define 
```c++
template<class matrix_t>
auto lange( const matrix_t& A){
   ...
}
template<class vector_t>
auto lange( const vector_t& v){
   ...
}
```
But this is a repeated definition of `lange`. A template type can be anything and the fact that we called it `matrix_t` does not mean anything to the compiler. To get this to work, we need to make complicated constructions with `enable_if`. With Concepts, it can simply be:
```c++
template<Matrix A_t>
auto lange( const A_t& A){
   ...
}
template<Vector V_t>
auto lange( const V_t& v){
   ...
}
```
### Clearer API

This one is simple, it seems much cleaner to me to have
```c++
template<Matrix A_t>
```
than to have
```c++
template<class A_t>
```

### Compiler support

I know that a solid argument against using c++20 features, or even c++17 features is compiler support. And yes, there are some compiler that don't yet support it fully. However, I don't think that <T>LAPACK is going to get a stable release anytime soon. Compiler support is more than good enough for us to develop with the library. Realistically, that kind of compiler support will only become required in ~2 years and at that point the c++20 standard will be 5 years old.

**Comment by weslleyspereira** [comment]
I like the idea of introducing concepts. I think you have strong arguments that they will help both users and developers in interpreting error messages. Thanks for organizing that!

I would like to make a suggestion in terms of how we could still allow compilers without C++20 to use our code. I think this is a clean way to activate and deactivate the usage of concepts:

```c++
#if __cplusplus >= 202002L
    // C++20 (and later) code
    #define TLAPACK_MATRIX MatrixConcept
    #define TLAPACK_VECTOR VectorConcept
#else
    #define TLAPACK_MATRIX class
    #define TLAPACK_VECTOR class
#endif
```

Then,

```c++
template <TLAPACK_MATRIX matrix_t, TLAPACK_VECTOR vector_t>
int geqr2(matrix_t& A, vector_t& tau){
   ...
}
```

I like the idea that someone can easily download and test \<T\>LAPACK without needing to install another compiler in their system. After a first successful test, one may want to have the best environment to work on the library. I say that because the cost for having that is currently zero.

-----

Now, you also stretch a new point: having the same interface of functions like `lange` working for both matrices and vectors. We still don't have that in the library. I think this should be addressed in another issue. In particular, and maybe coincidentally, I have been talking to @langou about that yesterday! We can discuss :) My idea above could still be used with slight changes.

**Comment by weslleyspereira** [comment]
I must say that you idea of using concepts looks way better than what I was trying to do in #32. Thanks!

**Comment by thijssteel** [comment]
I completely forgot about #32. I see that I was originally not convinced, but I have definitely changed my mind.

**Comment by thijssteel** [comment]
Something we need to figure out: Do we also differentiate between a general matrix and banded matrix using concepts? Because they should satisfy the same concept as matrices

**Comment by weslleyspereira** [comment]
> Something we need to figure out: Do we also differentiate between a general matrix and banded matrix using concepts? Because they should satisfy the same concept as matrices

I am not sure. I would say yes for that. Mind that the only routine that is currently specialized for banded matrices is `lascl`.

**Comment by weslleyspereira** [comment]
I will close this because of the recent #214 merged. We can reopen it or open a new issue if there is something else to be done. I didn't tackle banded matrices in #214.
