### ISSUE TITLE
lasy2 may not set scale and xnorm

### ISSUE THREAD

**Issue by weslleyspereira** [tlapack/tlapack#297]
`lasy2()` will not set `scale` and `xnorm` if:
- `n1 == 0 or n2 == 0`, or
- `n1 == 2 and n2 == 1`, or
- `n1 == 1 and n2 == 2`.

Should we start the routine by setting `scale` to 1 and `xnorm` to 0?

**Comment by weslleyspereira** [comment]
I think we have the same issue in the code in LAPACK.

**Comment by thijssteel** [comment]
I think this is just  a TODO for n1 == 2 and n2 == 1 in TLAPACK. I don't think LAPACK has the same issue.

If `n1 == 0 or n2 == 0` i guess it makes sense not to set those variables, the solution is kind of undefined.

But i guess it also makes sense to set `xnorm` to zero since the solution is an empty matrix.

**Comment by weslleyspereira** [comment]
> I think this is just a TODO for n1 == 2 and n2 == 1 in TLAPACK. I don't think LAPACK has the same issue.

Thanks for explaining. Now it makes sense to me. For some reason I saw the TODO and didn't understand. My bad.

> If `n1 == 0 or n2 == 0` i guess it makes sense not to set those variables, the solution is kind of undefined.
> 
> But i guess it also makes sense to set `xnorm` to zero since the solution is an empty matrix.

Thanks!
