### ISSUE TITLE
Dealing with complex and real values

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#30]
I think a good way to deal with complex values in the same file is a few overloads for real valued numbers:

- `real(x)` just returns `x`
- `imag(x)` returns 0
- 'conj(x)` returns `x`.

I think that at that point, we can just always write our code as we are writing it for complex numbers, and i'll work for real numbers as well.
The compiler is very likely going to optimize those values away for real values so there should be no performance hit.

**Comment by weslleyspereira** [comment]
Hi Thijs.

Thanks for the comment. I agree!

We are trying to apply these overloads whenever possible.

- The code currently uses `std::real` and `std::imag` that, since from C++11, already accept non-complex values.
- `conj(x) returns x`. In this case, we currently use the same strategy from BLAS++. See on [`utils.hpp`](https://github.com/tlapack/tlapack/blob/master/include/blas/utils.hpp):

```c++
/** Extend conj to real datatypes.
 * 
 * @usage:
 *     using blas::conj;
 *     scalar_t x = ...
 *     scalar_t y = conj( x );
 * 
 * @param[in] x Real number
 * @return x
 * 
 * @note C++11 to C++17 returns complex<real_t> instead of real_t. @see std::conj
 * 
 * @ingroup utils
 */
template< typename real_t >
inline real_t conj( const real_t& x )
{
    // This prohibits complex types; it can't be called as y = blas::conj( x ).
    static_assert( ! is_complex<real_t>::value,
                    "Usage: using blas::conj; y = conj(x); NOT: y = blas::conj(x);" );
    return x;
}
``` 

- Sometimes the algorithm changes considerably from real to complex, then I would argue that separate versions are clearer. This is the case of [`rotg`](https://github.com/tlapack/tlapack/blob/master/include/blas/rotg.hpp).

**Comment by thijssteel** [comment]
Ah that's great, I had no idea it was already implemented.
