### ISSUE TITLE
Out of bounds in geqr2

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#31]
I think i found a potential issue in geqr2. In the last iteration, `i` will be `k-1` and the start index of `x` is out of bounds. This isn't technically an issue because  `x` is also of size `0` and the value is never used, but with bounds checks enabled, this can be a problem.

https://github.com/tlapack/tlapack/blob/e99fdad4e9cad6573807b0624829f05899b8410e/include/lapack/geqr2.hpp#L82

**Comment by weslleyspereira** [comment]
I see. I agree it is a potential issue that, depending on the data structure, may lead to an error. LAPACK is using `MIN( I+1, M )` on `geqr2`: https://github.com/Reference-LAPACK/lapack/blob/2f132eee6e6bf96520f5c0b5ab82cbf32af15010/SRC/dgeqr2.f#L181. I also see a potential problem here:

https://github.com/tlapack/tlapack/blob/e99fdad4e9cad6573807b0624829f05899b8410e/include/lapack/geqr2.hpp#L92

LAPACK does not take care of the latter.

Solutions:

1. We can use the solution from LAPACK, i.e.: `pair{ std::min(m,i+1), m }`.

2. This kind of pattern may be present in other places. We may avoid taking some action now and highlight in the documentation: "we expect that pair{n,n} would not generate error since the interval will generate an array with dimension 0". This would avoid having many routines with `std::min`.

I would vote for using solution (1) in this case. If there are lots of places where the `std::min` should be used, then I would vote for (2).

**Comment by thijssteel** [comment]
`pair{ std::min(m,i+1), m }` does not work either, you'd need an even more complicated calculation

I definitely wouldn't go for option 2. Bounds checks are a very valuable tool for debugging.

**Comment by weslleyspereira** [comment]
> `pair{ std::min(m,i+1), m }` does not work either, you'd need an even more complicated calculation

Oh, I see... Sorry. Something like `(i+1 < m) ? pair{i+1,m} : pair{0,0}` would work. But it doesn't look that good to me.

A cleaner solution is to exit the loop before i+1=m (or before i+1==k). Then, consider the last step separately.
