### ISSUE TITLE
Error when building geqr2 example via make

### ISSUE THREAD

**Issue by rileyjmurray** [tlapack/tlapack#9]
The geqr2 example's README says it can be built with cmake or make. I populated make.inc with my installation information, but when I tried to run make I got the following output
```
(base) riley@borneophant:~/Documents/Research/protorandlapack/cpp/extern/tlapack/examples/geqr2$ make
g++ -I"/opt/tlapack/include" -Wall -pedantic -c -o example_geqr2.o example_geqr2.cpp
g++ -I"/opt/tlapack/include" -Wall -pedantic -o example_geqr2 example_geqr2.o -L"/opt/tlapack/lib" -ltblas
/usr/bin/ld: cannot find -ltblas
collect2: error: ld returned 1 exit status
```

I was able to get cmake to work. Is building this example with make still supported? If so, what's "tblas"?

**Comment by rileyjmurray** [comment]
Update: It builds with make and runs successfully after removing "-ltblas" this line from make.inc: https://github.com/tlapack/tlapack/blob/22d451d19e6a72ccb2c04149257626ac2c435d2a/examples/geqr2/make.inc#L7

**Comment by weslleyspereira** [comment]
Hi @rileyjmurray, thanks for noticing that! Indeed, I recently turned tblas into a header-only package so all `-ltblas` are wrong.
Would you like to create a PR to solve this?

Another thing is: I am not sure what is wrong with the `example_geqr2`. It runs as expected in my computer:
```
run< float  >( 7, 5 )
time = +7.81450e-02 ms,   GFlop/sec = +6.82492e-03
||QR - A||_F/||A||_F  = +1.53518e-07,        ||Q'Q - I||_F  = +6.22242e-07
-----------------------
run< double >( 7, 5 )
time = +8.29910e-02 ms,   GFlop/sec = +6.42640e-03
||QR - A||_F/||A||_F  = +2.52670e-16,        ||Q'Q - I||_F  = +9.09353e-16
-----------------------
run< long double >( 7, 5 )
time = +1.16634e-01 ms,   GFlop/sec = +4.57271e-03
||QR - A||_F/||A||_F  = +1.03292e-19,        ||Q'Q - I||_F  = +2.92372e-19
```
but it is completely wrong on the Github Actions (e.g., https://github.com/tlapack/tlapack/runs/5061265088?check_suite_focus=true):
```
 run< float  >( 7, 5 )
time = +4.00000e-04 ms,   GFlop/sec = +1.33333e+00
||QR - A||_F/||A||_F  = +1.03999e+00,        ||Q'Q - I||_F  = +5.86638e+00
-----------------------
run< double >( 7, 5 )
time = +2.00000e-04 ms,   GFlop/sec = +2.66667e+00
||QR - A||_F/||A||_F  = +5.83075e-01,        ||Q'Q - I||_F  = +5.44579e+00
-----------------------
run< long double >( 7, 5 )
time = +2.00000e-04 ms,   GFlop/sec = +2.66667e+00
||QR - A||_F/||A||_F  = +8.03419e-01,        ||Q'Q - I||_F  = +9.64909e+00
```

Please tell me if you find something weird. Thanks!

Also, I recently committed a more readable version of `example_geqr2` in 640dc35. Since you started looking at the code, I will avoid direct commits from now on.

**Comment by rileyjmurray** [comment]
@weslleyspereira happy to make a PR!

My ``example_geqr2`` works correctly. I'll be sure to let you know if I encounter failures there or elsewhere.
